logging:
  level:
    org.springframework.security: DEBUG

spring:
  h2:
    console:
      enabled: true

  datasource:
    initialize: true
    url: jdbc:h2:mem:auth;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: